const state = { promotions: [], categories: [], products: [], selected: null };
const $ = selector => document.querySelector(selector);
const money = pence => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format((pence || 0) / 100);
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const api = async (url, options = {}) => { const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data; };
const notice = (message, error = false) => { const node = $('#notice'); node.textContent = message; node.className = `notice ${error ? 'notice-error' : 'notice-success'}`; node.hidden = false; setTimeout(() => node.hidden = true, 5000); };
const localDate = value => value ? new Date(value).toISOString().slice(0, 16) : '';
const selectedValues = select => [...select.selectedOptions].map(option => option.value);

const renderRestrictions = () => { const value = $('#promotion-form').elements.appliesTo.value; $('#category-restriction').hidden = value !== 'specific_categories'; $('#product-restriction').hidden = value !== 'specific_products'; };
const renderValue = () => { const type = $('#promotion-form').elements.discountType.value; $('#discount-value-label').textContent = type === 'fixed_amount' ? 'Discount value (£)' : type === 'free_delivery' ? 'Discount value' : 'Discount value (%)'; $('#promotion-form').elements.discountValue.disabled = type === 'free_delivery'; $('#promotion-form').elements.discountValue.required = type !== 'free_delivery'; };
const renderList = () => {
  const query = $('#search').value.toLowerCase(); const status = $('#status-filter').value;
  const rows = state.promotions.filter(item => (!query || `${item.promotionName} ${item.discountCode}`.toLowerCase().includes(query)) && (!status || item.status === status));
  $('#promotion-list').innerHTML = rows.length ? rows.map(item => `<article class="promotion-row"><div><span class="promotion-code">${escapeHtml(item.discountCode)}</span><h3>${escapeHtml(item.promotionName)}</h3><p>${escapeHtml(item.promotionMessage)}</p><div class="promotion-meta"><span class="promotion-status ${item.status}">${item.status}</span><span>${escapeHtml(item.discountType.replaceAll('_', ' '))}</span><span>${item.showBanner ? 'Website banner on' : 'Banner off'}</span></div><div class="promotion-report"><strong>${item.uses} uses</strong><span>${money(item.revenueGenerated)} revenue</span><span>${money(item.totalDiscountGiven)} discounted</span></div></div><div class="promotion-actions"><button class="button button-secondary" data-edit="${item.id}">Edit</button><button class="button button-secondary" data-toggle="${item.id}">${item.active ? 'Disable' : 'Enable'}</button><button class="button button-secondary" data-duplicate="${item.id}">Duplicate</button><button class="mini-button" data-delete="${item.id}">Delete</button></div></article>`).join('') : '<div class="empty-promotion">No promotions match these filters.</div>';
};
const edit = promotion => {
  state.selected = promotion || null; const form = $('#promotion-form'); form.reset(); form.elements.id.value = promotion?.id || ''; $('#form-title').textContent = promotion ? 'Edit promotion' : 'New promotion';
  if (promotion) { for (const key of ['promotionName', 'promotionMessage', 'discountCode', 'discountType', 'maximumUses', 'maximumUsesPerCustomer', 'appliesTo']) form.elements[key].value = promotion[key] ?? ''; form.elements.discountValue.value = promotion.discountType === 'fixed_amount' ? promotion.discountValue / 100 : promotion.discountValue; form.elements.minimumOrderValue.value = promotion.minimumOrderValuePence ? promotion.minimumOrderValuePence / 100 : ''; form.elements.startDate.value = localDate(promotion.startDate); form.elements.endDate.value = localDate(promotion.endDate); form.elements.active.checked = promotion.active; form.elements.showBanner.checked = promotion.showBanner; [...form.elements.categoryIds.options].forEach(option => option.selected = promotion.categoryIds.includes(Number(option.value))); [...form.elements.productIds.options].forEach(option => option.selected = promotion.productIds.includes(option.value)); }
  renderRestrictions(); renderValue();
};
const load = async () => { const data = await api('/api/admin/discounts'); state.promotions = data.promotions; state.categories = data.categories; state.products = data.products; $('#promotion-form').elements.categoryIds.innerHTML = state.categories.map(item => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join(''); $('#promotion-form').elements.productIds.innerHTML = state.products.map(item => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join(''); $('#metric-discount').textContent = money(data.summary.totalDiscount); $('#metric-most-used').textContent = data.summary.mostUsed || '—'; $('#metric-active').textContent = data.summary.active; $('#metric-expired').textContent = data.summary.expired; renderList(); if (state.selected) edit(state.promotions.find(item => item.id === state.selected.id)); };

$('#promotion-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; const body = { id: form.elements.id.value ? Number(form.elements.id.value) : undefined, promotionName: form.elements.promotionName.value, promotionMessage: form.elements.promotionMessage.value, discountCode: form.elements.discountCode.value, discountType: form.elements.discountType.value, discountValue: form.elements.discountValue.value, active: form.elements.active.checked, showBanner: form.elements.showBanner.checked, startDate: form.elements.startDate.value || null, endDate: form.elements.endDate.value || null, maximumUses: form.elements.maximumUses.value || null, maximumUsesPerCustomer: form.elements.maximumUsesPerCustomer.value || null, minimumOrderValue: form.elements.minimumOrderValue.value || null, appliesTo: form.elements.appliesTo.value, categoryIds: selectedValues(form.elements.categoryIds), productIds: selectedValues(form.elements.productIds) }; try { await api('/api/admin/discounts', { method: body.id ? 'PUT' : 'POST', body: JSON.stringify(body) }); notice('Promotion saved.'); edit(null); await load(); } catch (error) { notice(error.message, true); } });
document.addEventListener('click', async event => { try { const id = Number(event.target.dataset.edit || event.target.dataset.toggle || event.target.dataset.duplicate || event.target.dataset.delete); if (event.target.dataset.edit) edit(state.promotions.find(item => item.id === id)); if (event.target.dataset.toggle) { const item = state.promotions.find(row => row.id === id); await api('/api/admin/discounts', { method: 'PUT', body: JSON.stringify({ ...item, active: !item.active, discountValue: item.discountType === 'fixed_amount' ? item.discountValue / 100 : item.discountValue, minimumOrderValue: item.minimumOrderValuePence ? item.minimumOrderValuePence / 100 : null }) }); await load(); } if (event.target.dataset.duplicate) { await api('/api/admin/discounts', { method: 'POST', body: JSON.stringify({ action: 'duplicate', id }) }); notice('Promotion duplicated as disabled.'); await load(); } if (event.target.dataset.delete && confirm('Delete this unused promotion?')) { await api('/api/admin/discounts', { method: 'DELETE', body: JSON.stringify({ id }) }); notice('Promotion deleted.'); edit(null); await load(); } } catch (error) { notice(error.message, true); } });
$('#new-promotion').addEventListener('click', () => edit(null)); $('#cancel-edit').addEventListener('click', () => edit(null)); $('#search').addEventListener('input', renderList); $('#status-filter').addEventListener('input', renderList); $('#promotion-form').elements.appliesTo.addEventListener('change', renderRestrictions); $('#promotion-form').elements.discountType.addEventListener('change', renderValue);
(async () => { try { const session = await api('/api/admin/session'); $('#admin-name').textContent = session.admin.name || 'Admin'; $('#admin-email').textContent = session.admin.email; $('#admin-initial').textContent = (session.admin.name || session.admin.email || 'A')[0].toUpperCase(); $('#discount-app').hidden = false; await load(); edit(null); } catch { $('#access-denied').hidden = false; } })();
