export const catalog = {
  'fried-plantain': { name: 'Fried Plantain', unitAmount: 1000 },
  'delife-yamarita': { name: 'DeLife Yamarita', unitAmount: 1200 },
  'egusi-soup': { name: 'Egusi Soup', unitAmount: 1500 },
  'fish-peppersoup': { name: 'Fish Peppersoup', unitAmount: 700 },
  'fried-rice': { name: 'Fried Rice', unitAmount: 1800 },
  'jollof-rice-chicken': { name: 'Jollof Rice & Chicken', unitAmount: 2000 },
  'jollof-rice': { name: 'Jollof Rice', unitAmount: 1200 },
  'meat-pie': { name: 'Meat Pie', unitAmount: 1500 },
  'moi-moi': { name: 'Moi Moi', unitAmount: 700 },
  nkwobi: { name: 'Nkwobi', unitAmount: 1500 },
  'nsala-soup': { name: 'Nsala Soup', unitAmount: 1300 },
  'okra-soup': { name: 'Okra Soup', unitAmount: 1700 },
  'stewed-chicken': { name: 'Stewed Chicken', unitAmount: 1400 },
  'stewed-turkey': { name: 'Stewed Turkey', unitAmount: 1300 },
  'stewed-turkey-2': { name: 'Stewed Turkey', unitAmount: 1300 },
  'tilapia-fish': { name: 'Tilapia Fish', unitAmount: 3300 },
  'yam-tomato-stew': { name: 'Yam & Tomato Stew', unitAmount: 3300 },
};
